### ISSUE TITLE
All issues combined.

### ISSUE THREAD

**Issue by MIkeBlackney1** [hellowearemito/dataconnector-facebook#5] opened 2017-10-27 13:22 UTC
I'm starting a new thread because I'm experiencing all of the issue stated in the other threads. 

 - Stuck at authorization stage: I removed the connector and started from scratch, and it worked.
 - Missing ad accounts: aside from it listing the accounts by Business Manager's company name and then ad account ID (which isn't ideal, but tolerable because I can find the corresponding company ID). Many ad accounts are missing. The missing ad accounts are ones for which I am an administrator as well, so there is no explanation for this.
 - Missing data: I decided to not choose a single ad account, but rather connect all of them. When I attempt to create a table/chart/etc. I get the same "configuration error as others have mentioned. 
 - Limited dimensions and metrics: very few of the potential Facebook Ads dimensions and metrics are available. Facebook Ads API makes hundreds of metrics available, but only 3 dimensions, and 7 metrics appear via this connector.

It appears that this connector isn't ready yet. Thanks to the developer for trying, but as of now it remains unusable.

**Comment by djozsef** [comment] 2017-10-27 15:27
Hello @MIkeBlackney1,

Thanks for the summary, but these facts are also noted in each issue. We prefer to handle then separately one by one at each separate issue's profile.
Most of the problems derive from the fact that Facebook randomly drops connection when querying large amount of data. We see that user use the connector without problem so we cannot call it a global issue. The fix for the Facebook connection drop problem is under development we plan to release an update to fix that in the coming days.
Please also note that we are working on a comprehensive update that covers adding more Insights metrics and dimensions.

As this issue is a duplicate of every other issues I close it now but thanks again to summarize it up.

**Closed as completed** 2017-10-27 15:27 UTC
