### ISSUE TITLE
Can't access Business Manager ad accounts

### ISSUE THREAD

**Issue by erikjd** [hellowearemito/dataconnector-facebook#9] opened 2018-01-30 13:23 UTC
Hi,

I cannot access my Business Manager ad account. I can access all my personal ad acount normally.

Thanks,

**Comment by santiagodemierre** [comment] 2018-01-30 21:08
Same here. opens dropdown box but everything is empty. 
Sidenote, this is after solving the authorization loop by login in on a incognito account. As I cannot login under the same account because it's a business account and not a personal account on facebook

**Comment by djozsef** [comment] 2018-02-06 13:09
Duplicate of #3

**Closed as completed by djozsef** 2018-02-06 13:09 UTC
