### ISSUE TITLE
Stuck at Authorisation stage

### ISSUE THREAD

**Issue by samarduoplus** [hellowearemito/dataconnector-facebook#4] opened 2017-10-04 21:57 UTC
Not able to go beyond "Native Facebook Connector requires authorization". I authorise successfully and close the window, but unable to go beyond that; back to the "Native Facebook Connector requires authorization" blue button again. What am I doing wrong?

**Comment by Kjetil-Digital-Ice** [comment] 2017-10-10 05:45
Same issue. This happened when I used my agency user which should give me access to multiple accounts. It says success, but when I go back it ask me to Authorize again...

**Comment by kevinennis** [comment] 2017-10-10 15:53
Same

**Comment by djozsef** [comment] 2017-10-10 22:04
Hello @samarduoplus @Kjetil-Digital-Ice @kevinennis ,

Thanks for reporting this issue, we have been able to reproduce it (thanks to @albertborsos).

Could you please check if this is the flow you got into? 
> When you have multiple live Google account logins you need to use and authroize Google Data Studio with the same Google Account that you would like to use the data connector. If you use different accounts you can get into the loop you have described.

**How to solve this issue?**
You need to revoke authroization from both Google Data Studio and our Native Facebook Connector and re-authorize. You can revoke permissions here: https://myaccount.google.com/permissions

**Comment by albertborsos** [comment] 2017-10-10 22:42
Not works to me. But try this:

- Open an incognito/private window in your browser.
- Log in to Facebook, then log in to your Google account.
- Open DataStudio then add the connector.

Then it will work in your normal browser window too.
That is kind of a Google bug, but this workaround solved my problem.

**Comment by djozsef** [comment] 2017-10-27 15:29
Removing and re-adding the connector is an other option to try. This is an internal issue between Data Studio and Google accounts.

**Comment by djozsef** [comment] 2017-11-02 16:34
Hello @Kjetil-Digital-Ice @Kjetil-Digital-Ice @kevinennis,

Could you please confirm if the solution from @albertborsos works for you guys? I managed to induce and solve the problem this way, just want to make sure this works for everyone.

Thanks.

**Comment by stemo-1975** [comment] 2017-12-08 10:24
The private mode works for me @djozsef.

**Comment by djozsef** [comment] 2017-12-08 11:50
Closing this issue as per no further problems reported.

**Closed as completed by djozsef** 2017-12-08 11:50 UTC

**Comment by christineosazuwa** [comment] 2018-05-17 13:18
I'm having this same issue and have tried all of the solutions outlined.
